name: yappsters
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  flutter_bloc: ^8.1.4
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  google_sign_in: ^6.2.1
  flutter_local_notifications: ^17.0.1
  cupertino_icons: ^1.0.6
  cloud_firestore: ^4.16.0
  firebase_messaging: ^14.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

